DROP DATABASE IF EXISTS SuperMarket;
CREATE DATABASE IF NOT EXISTS SuperMarket;
SHOW DATABASES;
USE SuperMarket;

DROP TABLE IF EXISTS Customer;
CREATE TABLE IF NOT EXISTS  Customer(
    custId VARCHAR(20),
    custTitle VARCHAR(100),
    custName VARCHAR(100) NOT NULL DEFAULT 'Unknown',
    custAddress VARCHAR(100) ,
    city VARCHAR(20),
    province VARCHAR(20),
    postalCode VARCHAR(20),
    CONSTRAINT PRIMARY KEY(custId)
);

SHOW TABLES;
DESCRIBE Customer;

DROP TABLE IF EXISTS `Order`;
CREATE TABLE IF NOT EXISTS  `Order`(
    orderId VARCHAR(20),
    custId VARCHAR(20),
    orderDate DATE,
    time VARCHAR(15),
    total DECIMAL(15,2),
    CONSTRAINT PRIMARY KEY (orderId),
    CONSTRAINT FOREIGN KEY (custId) REFERENCES Customer(custId) ON DELETE CASCADE ON UPDATE CASCADE
);
SHOW TABLES;
DESCRIBE `Order`;

DROP TABLE IF EXISTS Item;
CREATE TABLE IF NOT EXISTS Item(
    itemCode VARCHAR(20),
    description VARCHAR(100),
    packSize VARCHAR(20),
    unitPrice DECIMAL(15,2),
    qtyOnHand INT(10),
    discount DECIMAL(15,2),
     CONSTRAINT PRIMARY KEY (itemCode)
);
SHOW TABLES;
DESCRIBE Item;

DROP TABLE  IF EXISTS `Order Detail`;
CREATE TABLE IF NOT EXISTS `Order Detail`(
    orderId VARCHAR(20),
    itemCode VARCHAR(20),
    orderQty INT(10),
    discount DECIMAL(15,2),
    unitPrice DECIMAL(15,2),
    CONSTRAINT PRIMARY KEY (orderId, itemCode),
    CONSTRAINT FOREIGN key (orderId) REFERENCES `Order`(orderId) ON DELETE CASCADE  ON UPDATE CASCADE ,
    CONSTRAINT FOREIGN key (itemCode) REFERENCES Item(itemCode) ON DELETE CASCADE  ON UPDATE CASCADE
);
 SHOW TABLES;
 DESCRIBE `Order detail`;